import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { bytesToHex, hexToBytes, type Hex } from "viem";
import { StaticCollateralSource } from "../src/dcap/collateral.ts";
import type { TdxCollateral } from "../src/dcap/collateral.ts";
import { PcsCollateralSource as Pcs } from "../src/dcap/pcs.ts";
import { parseTdxQuote, verifyTdxQuote, type TdxVerification } from "../src/dcap/index.ts";
import { DcapQuoteVerifier } from "../src/verifier.ts";
import { dstackConfigMeasurement, tdxMeasurement, tdxReportData } from "../src/tdx-common.ts";
import type { Quote } from "../src/provider.ts";

const dir=new URL("./fixtures/intel-tdx/",import.meta.url),read=async(n:string)=>new Uint8Array(await readFile(new URL(n,dir))),json=async(n:string)=>JSON.parse(await readFile(new URL(n,dir),"utf8"));
const fixtureNow=1752919234;
function response(body:string|Uint8Array,headers:Record<string,string>={}){return new Response(body,{status:200,headers});}
function fetchFixture(c:TdxCollateral,root:Uint8Array){let calls=0;const f=async(input:string|URL)=>{calls++;const u=new URL(String(input));if(u.pathname.endsWith("/tdx/certification/v4/tcb"))return response(JSON.stringify({tcbInfo:JSON.parse(c.tcb_info),signature:c.tcb_info_signature}),{"TCB-Info-Issuer-Chain":encodeURIComponent(c.tcb_info_issuer_chain)});if(u.pathname.endsWith("/tdx/certification/v4/qe/identity"))return response(JSON.stringify({enclaveIdentity:JSON.parse(c.qe_identity),signature:c.qe_identity_signature}),{"SGX-Enclave-Identity-Issuer-Chain":encodeURIComponent(c.qe_identity_issuer_chain)});if(u.pathname.endsWith("/sgx/certification/v4/pckcrl"))return response(hexToBytes(`0x${c.pck_crl}`),{"SGX-PCK-CRL-Issuer-Chain":encodeURIComponent(c.pck_crl_issuer_chain)});return response(hexToBytes(`0x${c.root_ca_crl}`));};return{fetch:f as unknown as typeof fetch,count:()=>calls};}
describe("PCS collateral and DcapQuoteVerifier",()=>{
 test("PCS fetch converts Intel endpoints to collateral and verifies it; cache and HTTP errors",async()=>{const c=await json("tdx_quote_collateral.json") as TdxCollateral,root=await read("test/fixtures/intel-tdx/Intel_SGX_Provisioning_Certification_RootCA.cer").catch(async()=>read("Intel_SGX_Provisioning_Certification_RootCA.cer")),stub=fetchFixture(c,root),source=new Pcs({baseUrl:"https://pcs.test",rootCaCrlUrl:"https://root.test/crl",fetch:stub.fetch,now:()=>fixtureNow});const got=await source.get("B0C06F000000","platform");expect(got).toEqual(c);expect(verifyTdxQuote(await read("tdx_quote"),got,fixtureNow).status).toBe("UpToDate");await source.get("B0C06F000000","platform");expect(stub.count()).toBe(4);const reformat={...got,tcb_info:got.tcb_info.replace('"id":"TDX"','"id": "TDX"')},quoteRaw=await read("tdx_quote");expect(()=>verifyTdxQuote(quoteRaw,reformat,fixtureNow)).toThrow(/TCB signature/);const bad=new Pcs({baseUrl:"https://pcs.test",rootCaCrlUrl:"https://root.test/crl",now:()=>fixtureNow,fetch:(async()=>new Response("no",{status:503})) as unknown as typeof fetch});await expect(bad.get("B0C06F000000","platform")).rejects.toThrow("PCS HTTP 503");});
 test("real DCAP passes before Mochi REPORTDATA policy rejects its layout",async()=>{const raw=await read("tdx_quote"),c=await json("tdx_quote_collateral.json"),parsed=parseTdxQuote(raw),measurement=tdxMeasurement({mrtd:parseTdxQuote(raw).td.mrTd,rtmr:parseTdxQuote(raw).td.rtmr}),q:Quote={kind:"tdx",raw:bytesToHex(raw),measurement,reportData:`0x${"00".repeat(32)}`,issuedAt:0};const verifier=new DcapQuoteVerifier({collateral:new StaticCollateralSource(c),now:()=>fixtureNow});expect(await verifier.verify(q)).toEqual({ok:false,reason:"reportData layout"});expect((await verifier.verify(q)).reason).toBe("reportData layout");});
 test("policy runs after injected DCAP result and returns verified claims",async()=>{const raw=await read("tdx_quote"),c=await json("tdx_quote_collateral.json"),actual=verifyTdxQuote(raw,c,fixtureNow),binding=`0x${"ab".repeat(32)}` as Hex,issuedAt=fixtureNow-12,td={...actual.td,tdAttributes:new Uint8Array(8),reportData:tdxReportData(binding,issuedAt)},synthetic:TdxVerification={...actual,td},measurement=tdxMeasurement({mrtd:td.mrTd,rtmr:td.rtmr}),q:Quote={kind:"tdx",raw:bytesToHex(raw),measurement,reportData:binding,issuedAt},base={collateral:new StaticCollateralSource(c),now:()=>fixtureNow,verifyDcap:()=>synthetic};expect(await new DcapQuoteVerifier(base).verify({...q,kind:"mock"})).toEqual({ok:false,reason:"wrong quote kind"});expect((await new DcapQuoteVerifier(base).verify(q)).ok).toBe(true);expect((await new DcapQuoteVerifier({...base,policy:{allowedStatuses:["OutOfDate"]}}).verify(q)).reason).toBe("tcb status UpToDate");expect((await new DcapQuoteVerifier({ ...base,policy:{rejectAdvisories:["INTEL-SA-X"]},verifyDcap:()=>({...synthetic,advisoryIds:["INTEL-SA-X"]})}).verify(q)).reason).toBe("rejected advisory");const debugTd={...td,tdAttributes:Uint8Array.from([1,0,0,0,0,0,0,0])};expect((await new DcapQuoteVerifier({...base,verifyDcap:()=>({...synthetic,td:debugTd})}).verify(q)).reason).toBe("debug TD");expect((await new DcapQuoteVerifier(base).verify({...q,measurement:`0x${"cd".repeat(32)}`})).reason).toBe("measurement field mismatch");expect((await new DcapQuoteVerifier(base).verify(q,{measurement:`0x${"cd".repeat(32)}`})).reason).toBe("unexpected measurement");expect((await new DcapQuoteVerifier(base).verify(q,{reportData:`0x${"cd".repeat(32)}`})).reason).toBe("unexpected reportData");expect((await new DcapQuoteVerifier(base).verify({...q,reportData:`0x${"cd".repeat(32)}`})).reason).toBe("reportData field mismatch");expect((await new DcapQuoteVerifier({...base,verifyDcap:()=>({...synthetic,td:{...td,reportData:new Uint8Array(63)}})}).verify(q)).reason).toBe("reportData layout");expect((await new DcapQuoteVerifier(base).verify({...q,issuedAt:issuedAt+1})).reason).toBe("issuedAt field mismatch");expect((await new DcapQuoteVerifier(base).verify(q,{maxAgeSec:1})).reason).toContain("expired");expect((await new DcapQuoteVerifier({...base,now:()=>issuedAt-61}).verify(q,{maxAgeSec:300})).reason).toContain("future");expect(await new DcapQuoteVerifier({...base,policy:{allowDebug:true}}).verify(q)).toMatchObject({ok:true,measurement,reportData:binding,tcbStatus:"UpToDate",advisoryIds:[]});});
 test("explicit dstack profile is measured only after full DCAP and never falls back to the legacy pin",async()=>{const raw=await read("tdx_quote"),c=await json("tdx_quote_collateral.json"),actual=verifyTdxQuote(raw,c,fixtureNow),binding=`0x${"ab".repeat(32)}` as Hex,issuedAt=fixtureNow-12,config=new Uint8Array(48);config[0]=1;config.fill(0x5a,1,33);const td={...actual.td,tdAttributes:new Uint8Array(8),mrConfigId:config,reportData:tdxReportData(binding,issuedAt)},synthetic:TdxVerification={...actual,td},base={collateral:new StaticCollateralSource(c),now:()=>fixtureNow,verifyDcap:()=>synthetic},legacyPin=tdxMeasurement({mrtd:td.mrTd,rtmr:td.rtmr}),stablePin=dstackConfigMeasurement({mrtd:td.mrTd,mrConfigId:td.mrConfigId,rtmr:td.rtmr}),q:Quote={kind:"tdx",raw:bytesToHex(raw),measurement:stablePin,measurementScheme:"dstack-config-v1",reportData:binding,issuedAt};expect((await new DcapQuoteVerifier(base).verify(q)).ok).toBe(true);expect((await new DcapQuoteVerifier(base).verify({...q,measurement:legacyPin})).reason).toBe("measurement field mismatch");expect((await new DcapQuoteVerifier(base).verify({...q,measurementScheme:"future-profile" as never})).reason).toBe("unknown measurement scheme");const malformed={...td,mrConfigId:new Uint8Array(48)};expect((await new DcapQuoteVerifier({...base,verifyDcap:()=>({...synthetic,td:malformed})}).verify(q)).reason).toBe("invalid measurement profile");});
 test("outdated quote is rejected at the unsupported platform TCB level",async()=>{const raw=await read("tdx_quote_outdated"),c=await json("tdx_quote_outdated_collateral.json"),parsed=parseTdxQuote(raw),measurement=tdxMeasurement({mrtd:parsed.td.mrTd,rtmr:parsed.td.rtmr}),q:Quote={kind:"tdx",raw:bytesToHex(raw),measurement,reportData:("0x"+"00".repeat(32)) as Hex,issuedAt:0},source=new StaticCollateralSource(c);expect((await new DcapQuoteVerifier({collateral:source,now:()=>1774003274}).verify(q)).reason).toBe("dcap: TCB not supported");});

 test("collateral source errors are distinct from quote verification errors",async()=>{const raw=await read("tdx_quote"),parsed=parseTdxQuote(raw),measurement=tdxMeasurement({mrtd:parsed.td.mrTd,rtmr:parsed.td.rtmr}),quote:Quote={kind:"tdx",raw:bytesToHex(raw),measurement,reportData:("0x"+"00".repeat(32)) as Hex,issuedAt:0};const missing=new DcapQuoteVerifier();expect((await missing.verify(quote)).reason).toBe("dcap: collateral source required");const unavailable=new DcapQuoteVerifier({collateral:{get:async()=>{throw new Error("network down");}}});expect((await unavailable.verify(quote)).reason).toBe("dcap: collateral unavailable");});
});
