import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { bytesToHex, hexToBytes } from "viem";
import { sha256 } from "@noble/hashes/sha2.js";
import { p256 } from "@noble/curves/nist.js";
import { INTEL_SGX_ROOT_CA_DER, parseCert, parseCrl, parseTdxQuote, pemChain, verifyTdxQuote } from "../src/dcap/index.ts";
import { DcapError, assertSerialNotRevoked, convergeTcbStatus, convergeTcbStatuses } from "../src/dcap/verify.ts";
import { children, integer, readTlv } from "../src/dcap/der.ts";

const dir=new URL("./fixtures/intel-tdx/",import.meta.url);
const read=async(name:string)=>new Uint8Array(await readFile(new URL(name,dir)));
const json=async(name:string)=>JSON.parse(await readFile(new URL(name,dir),"utf8"));
const same=(a:Uint8Array,b:Uint8Array)=>expect([...a]).toEqual([...b]);
// nosemgrep: detect-non-literal-regexp -- key is a fixed snapshot field name from this test
function snapArray(s:string,key:string):number[] {const m=new RegExp(`\\b${key}: \\[([\\s\\S]*?)\\]`).exec(s);if(!m)throw new Error(`snapshot field missing ${key}`);return [...m[1]!.matchAll(/\d+/g)].map(x=>Number(x[0]));}
describe("Intel TDX DCAP",()=>{
 test("pinned root matches Intel fixture",async()=>{const root=await read("Intel_SGX_Provisioning_Certification_RootCA.cer");same(INTEL_SGX_ROOT_CA_DER,root);expect(bytesToHex(sha256(root))).toBe("0x44a0196b2b99f889b8e149e95b807a350e7424964399e885a7cbb8ccfab674d3");});
 test("v4 fields match dcap-qvl snapshot arrays",async()=>{const q=parseTdxQuote(await read("tdx_quote")),snap=await readFile(new URL("verify_quote__could_parse_tdx_quote.snap",dir),"utf8");for(const [key,val] of [["tee_tcb_svn",q.td.teeTcbSvn],["mr_seam",q.td.mrSeam],["mr_signer_seam",q.td.mrSignerSeam],["seam_attributes",q.td.seamAttributes],["td_attributes",q.td.tdAttributes],["xfam",q.td.xfam],["mr_td",q.td.mrTd],["mr_config_id",q.td.mrConfigId],["mr_owner",q.td.mrOwner],["mr_owner_config",q.td.mrOwnerConfig],["rt_mr0",q.td.rtmr[0]],["rt_mr1",q.td.rtmr[1]],["rt_mr2",q.td.rtmr[2]],["rt_mr3",q.td.rtmr[3]],["report_data",q.td.reportData],["ecdsa_signature",q.signature],["ecdsa_attestation_key",q.attestationKey],["qe_report",q.qeReport],["qe_report_signature",q.qeSignature],["data",q.qeAuthData]] as [string,Uint8Array][])same(val,Uint8Array.from(snapArray(snap,key)));same(q.header.qeVendorId,Uint8Array.from(snapArray(snap,"qe_vendor_id")));same(q.header.userData,Uint8Array.from(snapArray(snap,"user_data")));expect(q.header.version).toBe(Number(/version: (\d+)/.exec(snap)?.[1]));expect(q.header.attestationKeyType).toBe(Number(/attestation_key_type: (\d+)/.exec(snap)?.[1]));expect(q.header.teeType).toBe(Number(/tee_type: (\d+)/.exec(snap)?.[1]));expect(q.header.qeSvn).toBe(Number(/qe_svn: (\d+)/.exec(snap)?.[1]));expect(q.header.pceSvn).toBe(Number(/pce_svn: (\d+)/.exec(snap)?.[1]));expect(q.version).toBe(4);expect(q.bodySize).toBe(584);expect(pemChain(q.pckPem).map(c=>c.subjectCN)).toContain("Intel SGX Root CA");});
 test("fresh quote verifies; outdated quote reaches TCB and has no supported level",async()=>{const result=verifyTdxQuote(await read("tdx_quote"),await json("tdx_quote_collateral.json"),1752919234),outdated=await read("tdx_quote_outdated"),oldCollateral=await json("tdx_quote_outdated_collateral.json");expect([result.status,result.advisoryIds,result.fmspc,result.quoteVersion]).toEqual(["UpToDate",[],"B0C06F000000",4]);expect(()=>verifyTdxQuote(outdated,oldCollateral,1774003274)).toThrow("TCB not supported");});
 test("tampering and untrusted roots fail closed",async()=>{const quote=await read("tdx_quote"),col=await json("tdx_quote_collateral.json");const body=quote.slice();body[100]=(body[100]??0)^1;expect(()=>verifyTdxQuote(body,col,1752919234)).toThrow(/quote signature/);const parsed=parseTdxQuote(quote);const qe=quote.slice();qe[parsed.signed.length+4+64+64+6+10]=(qe[parsed.signed.length+4+64+64+6+10]??0)^1;expect(()=>verifyTdxQuote(qe,col,1752919234)).toThrow(/QE report signature/);const key=quote.slice();key[parsed.signed.length+4+64+3]=(key[parsed.signed.length+4+64+3]??0)^1;expect(()=>verifyTdxQuote(key,col,1752919234)).toThrow(/QE report data/);expect(()=>verifyTdxQuote(quote,col,1752919234,{trustedRootDer:pemChain(col.tcb_info_issuer_chain)[0]!.der})).toThrow("untrusted root");const changed={...col,tcb_info:col.tcb_info.replace('"id":"TDX"','"id": "TDX"')};expect(()=>verifyTdxQuote(quote,changed,1752919234)).toThrow(/TCB signature/);const changedQe={...col,qe_identity:col.qe_identity.replace('"id":"TD_QE"','"id": "TD_QE"')};expect(()=>verifyTdxQuote(quote,changedQe,1752919234)).toThrow(/QE identity signature/);const other=await json("tdx_quote_outdated_collateral.json");expect(()=>verifyTdxQuote(quote,other,1752919234)).toThrow();});
 test("collateral validity is bounded and CRL exposes revoked serials",async()=>{const col=await json("tdx_quote_collateral.json"),start=Date.parse("2025-06-19T10:32:27Z")/1000,end=Date.parse("2025-07-19T10:00:35Z")/1000,q=await read("tdx_quote");expect(()=>verifyTdxQuote(q,col,start-1)).toThrow(DcapError);expect(()=>verifyTdxQuote(q,col,end+1)).toThrow(DcapError);const crl=parseCrl(hexToBytes(`0x${col.pck_crl}`));expect(crl.revoked.size).toBeGreaterThan(0);expect([...crl.revoked].every(x=>typeof x==="bigint")).toBe(true);const listed=[...crl.revoked][0]!;expect(()=>assertSerialNotRevoked(listed,crl)).toThrow("certificate revoked");});
 test("fixture certificate has a high-S signature and verifies it",async()=>{const q=parseTdxQuote(await read("tdx_quote")),cert=pemChain(q.pckPem)[0]!,parts=children(readTlv(cert.signature)),s=integer(parts[1]!),n=BigInt("0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551");expect(s>n/2n).toBe(true);expect(p256.verify(cert.signature,cert.tbs,pemChain(q.pckPem)[1]!.publicKey,{lowS:false,prehash:true,format:"der"})).toBe(true);});
 test("truncated and invalid inputs throw; any all-zero padding is allowed",async()=>{const raw=await read("tdx_quote");for(const n of [0,1,47,48,631,632,raw.length-71])expect(()=>parseTdxQuote(raw.slice(0,n))).toThrow();for(const [at,b] of [[0,3],[2,1],[4,0],[48+584+4+64+64,0]] as [number,number][]) {const x=raw.slice();x[at]=b;expect(()=>parseTdxQuote(x)).toThrow();}expect(parseTdxQuote(Uint8Array.from([...raw,0])).version).toBe(4);expect(()=>parseTdxQuote(Uint8Array.from([...raw,1]))).toThrow("quote trailing bytes");});

 test("signed collateral text is exact and wrappers cannot replace parsed fields",async()=>{const raw=await read("tdx_quote"),collateral=await json("tdx_quote_collateral.json"),tcbBody=collateral.tcb_info,qeBody=collateral.qe_identity;const wrappedTcb=JSON.stringify({id:"TDX",version:3,tcbLevels:[{tcb:{pcesvn:0,sgxtcbcomponents:Array(16).fill({svn:0}),tdxtcbcomponents:Array(16).fill({svn:0})},tcbStatus:"UpToDate"}]}).slice(0,-1)+`,"tcbInfo":${tcbBody}}`;expect(wrappedTcb.includes(tcbBody)).toBe(true);expect(()=>verifyTdxQuote(raw,{...collateral,tcb_info:wrappedTcb},1752919234)).toThrow("TCB signature");const wrappedQe=JSON.stringify({id:"TD_QE",version:2,tcbLevels:[{tcb:{isvsvn:0},tcbStatus:"UpToDate"}]}).slice(0,-1)+`,"enclaveIdentity":${qeBody}}`;expect(wrappedQe.includes(qeBody)).toBe(true);expect(()=>verifyTdxQuote(raw,{...collateral,qe_identity:wrappedQe},1752919234)).toThrow("QE identity signature");expect(()=>verifyTdxQuote(raw,{...collateral,tcb_info:tcbBody+" "},1752919234)).toThrow("TCB signature");});

 test("issuer chain shapes and signer names are enforced",async()=>{const raw=await read("tdx_quote"),collateral=await json("tdx_quote_collateral.json");expect(()=>verifyTdxQuote(raw,{...collateral,tcb_info_issuer_chain:collateral.tcb_info_issuer_chain+collateral.tcb_info_issuer_chain.split("-----END CERTIFICATE-----")[0]+"-----END CERTIFICATE-----"},1752919234)).toThrow();expect(()=>verifyTdxQuote(raw,{...collateral,tcb_info_issuer_chain:collateral.pck_crl_issuer_chain},1752919234)).toThrow("TCB signer CN");});

 test("status convergence follows Intel QVL convergeTcbStatuses: only OutOfDate and Revoked components change the platform status",()=>{const statuses=["UpToDate","SWHardeningNeeded","ConfigurationNeeded","ConfigurationAndSWHardeningNeeded","OutOfDate","OutOfDateConfigurationNeeded","Revoked"];const [U,S,C,CS,O,OC,R]=statuses as [string,string,string,string,string,string,string];const table:Record<string,string[]>={UpToDate:[U,U,U,U,O,U,R],SWHardeningNeeded:[S,S,S,S,O,S,R],ConfigurationNeeded:[C,C,C,C,OC,C,R],ConfigurationAndSWHardeningNeeded:[CS,CS,CS,CS,OC,CS,R],OutOfDate:[O,O,O,O,O,O,R],OutOfDateConfigurationNeeded:[OC,OC,OC,OC,OC,OC,R],Revoked:[R,R,R,R,R,R,R]};for(const platform of statuses)statuses.forEach((component,index)=>expect(convergeTcbStatus(platform,component)).toBe(table[platform]![index]!));expect(convergeTcbStatuses(U,[O,R])).toBe(R);expect(convergeTcbStatuses(C,[U,O])).toBe(OC);expect(convergeTcbStatuses(S,[])).toBe(S);expect(()=>convergeTcbStatus("Unknown","UpToDate")).toThrow("unknown TCB status");});
});
