// Generates packages/chain/src/abis.ts from Foundry artifacts (run after `forge build` in contracts/).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "contracts/out");
const CONTRACTS = [
  "MochiToken",
  "BlockhashRandomness",
  "DrandRandomness",
  "SchemaRegistry",
  "JurorRegistry",
  "QueryEscrow",
  "MochiVerdicts",
  "Feeds",
  "StockTokenCrosscheck",
  "PanelEscalation",
  "MochiStaking",
  "ReceiptAnchor",
  "ClassMix",
  "ClerkVoting",
  "DisclosureRegistry",
  "MochiTimelock",
  "EarningsBeatMarket",
  "MockUSDG",
  "MockShieldedPayments",
  "MockStockToken",
  "Entrypoint",
  "PrivacyPoolComplex",
  "WithdrawalVerifier",
  "CommitmentVerifier",
  "ERC1967Proxy",
  "PrivacyPoolShieldedPayments",
];

let src = "// GENERATED by scripts/gen-abis.ts from contracts/out — do not edit.\n\n";
for (const name of CONTRACTS) {
  const file = join(OUT, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) throw new Error(`missing artifact ${file} — run forge build`);
  const art = JSON.parse(readFileSync(file, "utf8"));
  src += `export const ${name}Abi = ${JSON.stringify(art.abi)} as const;\n\n`;
  src += `export const ${name}Bytecode = ${JSON.stringify(art.bytecode.object)} as \`0x\${string}\`;\n\n`;
}
writeFileSync(join(ROOT, "packages/chain/src/abis.ts"), src);
console.log(`wrote ${CONTRACTS.length} ABIs`);
