import './zod-jitless.js';
import {DashboardEntry} from './live-dashboard.jsx';
import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{fixtures,modelClasses,schemas}from'./fixtures';
const tabs=['Overview','New query','Verdicts','Feeds','Disagreement'];
function readStore(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback}catch{return fallback}}
function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function Button({children,onClick,secondary=false,...props}){return <button className={'work-button'+(secondary?' secondary':'')} onClick={onClick} {...props}>{children}</button>}
// Schema field keys (reported_reserves) read as words and may wrap; an unbroken key overflowed its grid track.
const fieldLabel=name=>name.replaceAll('_',' ');
function Status({value}){return <span className={'work-status '+(value==='HUNG'?'hung':'')}>{value}</span>}
function App(){
 const initial=new URLSearchParams(location.search).get('sample');
 const [tab,setTab]=useState(initial?'New query':'Overview'),[sample,setSample]=useState(fixtures[initial]?initial:''),[source,setSource]=useState(fixtures[initial]?.source||''),[schema,setSchema]=useState(fixtures[initial]?.schema||'EARNINGS'),[jurySize,setJurySize]=useState(3),[privacy,setPrivacy]=useState(true),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[history,setHistory]=useState(()=>readStore('mochi-demo-history',[])),[watched,setWatched]=useState(()=>readStore('mochi-demo-feeds',[])),[filter,setFilter]=useState(''),[statusFilter,setStatusFilter]=useState('ALL');
 const timer=useRef(null),dialog=useRef(null),formRef=useRef(null);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useEffect(()=>{try{localStorage.setItem('mochi-demo-history',JSON.stringify(history))}catch{}},[history]);
 useEffect(()=>{try{localStorage.setItem('mochi-demo-feeds',JSON.stringify(watched))}catch{}},[watched]);
 function navigate(t){clearTimeout(timer.current);setBusy(false);setTab(t);setError('');setMessage('');setFilter('');setResult(null);document.querySelector('[data-scroll-wrapper]').scrollTo({top:0});}
 function loadSample(key){navigate('New query');setSample(key);setSource(fixtures[key].source);setSchema(fixtures[key].schema);setJurySize(3);}
 function run(e){e.preventDefault();setError('');setMessage('');setResult(null);if(!source.trim()){setError('Add a document or choose a sample to continue.');formRef.current?.querySelector('textarea')?.focus();return}if(source.length>100000){setError('Keep the local preview below 100,000 characters.');return}
  if(sample&&source===fixtures[sample].source&&schema===fixtures[sample].schema&&jurySize===3){setBusy(true);timer.current=setTimeout(()=>{const r={...fixtures[sample],createdAt:new Date().toISOString(),runId:crypto.randomUUID(),sample:true,attestation:'NOT_CONNECTED',chainReceipt:null};setResult(r);setHistory(h=>[r,...h].slice(0,30));setBusy(false)},700)}
  else{const packet={kind:'LOCAL_REQUEST_DRAFT',schema,jurySize,privacy:privacy?'private-requested':'public-requested',document:source,createdAt:new Date().toISOString(),delivery:'NOT_SUBMITTED'};setResult({draft:packet});setMessage('Request prepared on this device. Download the draft to inspect it. No document was uploaded and no model run, payment or attestation occurred.');}
 }
 async function upload(e){const file=e.target.files?.[0];if(!file)return;setError('');if(file.size>100000){setError('Use a text file smaller than 100 KB.');e.target.value='';return}if(!/\.(txt|md|csv)$/i.test(file.name)){setError('This local preview accepts .txt, .md and .csv. PDF processing belongs in the live enclave pipeline.');e.target.value='';return}try{setSource(await file.text());setSample('');setResult(null);setMessage(file.name+' loaded locally. It has not been uploaded.')}catch{setError('The file could not be read. Paste the text instead.')}}
 function inspect(r){navigate('Verdicts');setResult(r)}
 const all=[...history,...Object.values(fixtures).map(r=>({...r,sample:true,runId:r.id,createdAt:null}))];
 const visible=all.filter(r=>(statusFilter==='ALL'||r.status===statusFilter)&&(r.title+' '+r.schema).toLowerCase().includes(filter.toLowerCase()));
 return <div className="workspace">
  <aside className="workspace-rail"><div className="rail-brand">MOCHI<small>Model jury workspace</small></div><nav className="workspace-tabs" aria-label="Workspace">{tabs.map(t=><button key={t} className={tab===t?'active':''} aria-current={tab===t?'page':undefined} onClick={()=>navigate(t)}>{t}</button>)}</nav><div className="rail-footer"><p>Sample workspace<br/>Saved history stays on this device.</p><a href="/docs/">Developer documentation ↗</a><br/><br/><a href="/">Back to MOCHI ↗</a></div></aside>
  <div className="workspace-body"><div className="workspace-kicker"><span>● SAMPLE WORKSPACE</span><span>MOCHI / {String(tabs.indexOf(tab)+1).padStart(2,'0')}</span></div><h1 className="workspace-title">{tab==='Overview'?'Review overview.':tab==='New query'?'Prepare a review.':tab==='Disagreement'?'Assess disagreement.':tab+'.'}</h1><p className="workspace-note">Explore the review flow with sample data. Live inference, payments and on-chain attestations are not connected.</p>
  {error&&<div className="work-message error" role="alert">{error}</div>}{message&&<div className="work-message" role="status">{message}</div>}
  {tab==='Overview'&&<><div className="workspace-stats"><div className="workspace-stat"><strong>07</strong><span>Document schemas</span></div><div className="workspace-stat"><strong>03</strong><span>AI jurors at launch</span></div><div className="workspace-stat"><strong>100%</strong><span>Agreement required: all 3 jurors</span></div></div><h2>Sample decisions</h2><div className="review-cards"><article className="review-card"><div><small>01 / VERDICT</small><h3>All three jurors agree.</h3><p>Each juror reports EPS of 2.11 and revenue of 1.28B, quoting the same release. Review the readings and their evidence.</p></div><Button onClick={()=>loadSample('earnings')}>Review earnings <span>↗</span></Button></article><article className="review-card"><div><small>02 / HUNG</small><h3>Conflicting reserve figures.</h3><p>The summary reports 100M in reserves. The supporting schedule reports 98M.</p></div><Button onClick={()=>loadSample('reserves')}>Review reserves <span>↗</span></Button></article></div><h2>Recent sample records</h2><Records rows={all.slice(0,5)} inspect={inspect}/><Button onClick={()=>navigate('New query')}>Prepare a new query <span>→</span></Button></>}
  {tab==='New query'&&<><div className="work-actions"><Button secondary onClick={()=>loadSample('claim')}>Load claim check sample</Button><Button secondary onClick={()=>loadSample('earnings')}>Load earnings sample</Button><Button secondary onClick={()=>loadSample('reserves')}>Load HUNG sample</Button></div><form ref={formRef} className="work-form" onSubmit={run} noValidate><fieldset disabled={busy} style={{display:'contents'}}><div className="field-row"><label>Task schema<select value={schema} onChange={e=>{setSchema(e.target.value);setResult(null)}}>{schemas.map(s=><option key={s}>{s}</option>)}</select></label><label>Jury size<select value={jurySize} onChange={e=>{setJurySize(Number(e.target.value));setResult(null)}}><option value={3}>3 AI jurors</option></select><small>Every check at launch uses 3 jurors. Larger juries, up to 9, are configurable later.</small></label></div><label>Document text<textarea value={source} onChange={e=>{setSource(e.target.value);setSample('');setResult(null)}} placeholder="Paste a notice, statement or release, or load a sample above." maxLength={100001}/></label><label>Load a local text file<input type="file" accept=".txt,.md,.csv" onChange={upload}/></label><label className="check-field"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)}/><span>Request private disclosure<br/><small>A request preference; live encryption and access controls are not connected.</small></span></label></fieldset><div className="work-actions"><Button type="submit" disabled={busy}>{busy?'Reviewing sample…':sample&&jurySize===3&&schema===fixtures[sample]?.schema?'Run sample review':'Prepare local request'} <span>→</span></Button>{busy&&<Button type="button" secondary onClick={()=>{clearTimeout(timer.current);setBusy(false);setMessage('Sample review cancelled.')}}>Cancel</Button>}</div></form></>}
  {tab==='Verdicts'&&<><div className="work-toolbar"><input className="work-filter" aria-label="Search verdicts" placeholder="Search issuer or schema" value={filter} onChange={e=>setFilter(e.target.value)}/><select className="work-filter" aria-label="Filter by status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All outcomes</option><option>VERDICT</option><option>HUNG</option></select><Button secondary onClick={()=>dialog.current.showModal()} disabled={!history.length}>Clear saved runs</Button></div><Records rows={visible} inspect={setResult}/></>}
  {tab==='Feeds'&&<><h2>Recurring document review.</h2><p>Watch preferences are stored on this device. They do not create a paid subscription.</p>{[['Corporate actions','Ex-date and split notices with multiplier cross-checks.'],['Earnings','Release-day EPS and revenue with evidence and dissent.'],['Attestations','Reserve and NAV statements compared with source records.']].map(([name,description],i)=><article className="feed-row" key={name}><div><small>0{i+1} / PLANNED FEED</small><h3>{name}</h3><p>{description}</p><small>Live source: not connected · Last verified update: unavailable</small></div><div><Button secondary onClick={()=>setWatched(w=>w.includes(name)?w.filter(x=>x!==name):[...w,name])}>{watched.includes(name)?'Watching locally ✓':'Watch locally +'}</Button></div></article>)}<div className="work-message">A HUNG verdict or failed cross-check must not update a live feed. Freshness and provenance must be available to every consumer.</div></>}
  {tab==='Disagreement'&&<><div className="workspace-stats"><div className="workspace-stat"><strong>{String(Object.keys(fixtures).length).padStart(2,'0')}</strong><span>Illustrative samples</span></div><div className="workspace-stat"><strong>{String(Object.values(fixtures).flatMap(r=>r.fields.filter(f=>f.agreement<100)).length).padStart(2,'0')}</strong><span>Fields with dissent</span></div><div className="workspace-stat"><strong>01</strong><span>Unresolved outcome</span></div></div><p>Summary of the built-in samples. Live network analytics are not connected.</p><h2>Field-level disagreement</h2>{Object.values(fixtures).flatMap(r=>r.fields.filter(f=>f.agreement<100).map(f=><div className="field-agreement" key={f.name}><span>{fieldLabel(f.name)}</span><div className="agreement-track" aria-label={(100-f.agreement)+' percent disagreement'}><span style={{width:(100-f.agreement)+'%'}}/></div><span>{100-f.agreement}%</span></div>))}<div className="work-actions"><Button onClick={()=>loadSample('reserves')}>Inspect the unresolved field <span>→</span></Button></div></>}
  {result?.draft&&<section className="work-result"><h2>Local request draft</h2><pre className="mochi-code">{JSON.stringify({...result.draft,document:'['+result.draft.document.length+' characters. included in downloaded draft]'},null,2)}</pre><Button onClick={()=>download(result.draft,'mochi-request-draft.json')}>Download request JSON <span>↓</span></Button></section>}
  {result&&!result.draft&&<Result data={result} setMessage={setMessage}/>}
  <dialog ref={dialog} className="work-modal"><h2>Clear saved sample runs?</h2><p>This removes the demonstration history on this device. The built-in samples remain available.</p><div className="work-actions"><Button onClick={()=>{setHistory([]);setResult(null);dialog.current.close();setMessage('Saved sample runs cleared.')}}>Clear saved runs</Button><Button secondary onClick={()=>dialog.current.close()}>Keep history</Button></div></dialog>
 </div></div>
}
// A juror bar is highlighted when it disagrees with the majority answer on the least-agreed field.
function agreesWithMajority(r,i){const field=r.fields.reduce((a,f)=>f.agreement<a.agreement?f:a,r.fields[0]);const answers=field.answers;const majority=answers.find(a=>answers.filter(b=>b===a).length*2>answers.length);return majority===undefined||answers[i]===majority}
function Records({rows,inspect}){return rows.length?<div className="work-table-wrap"><table className="work-table"><thead><tr><th>Document</th><th>Outcome</th><th>Agreement</th><th>Source</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.runId||i}><td><button onClick={()=>inspect(r)}>{r.title}</button><br/><small>{r.schema}</small></td><td><Status value={r.status}/></td><td>{r.agreement}%</td><td>{r.createdAt?'Local sample run':'Sample record'}</td></tr>)}</tbody></table></div>:<div className="work-empty">No sample verdicts match this filter. Try another issuer or outcome.</div>}
function Result({data:r,setMessage}){return <section className="work-result" aria-label="Decision packet"><div className="result-top"><div><small>DECISION PACKET / SAMPLE</small><h2>{r.title}</h2><Status value={r.status}/></div><strong>{r.agreement}%<small>Minimum field agreement</small></strong></div><div className="jury-visual" aria-hidden="true">{modelClasses.map((m,i)=>{const agrees=agreesWithMajority(r,i);return <span key={m} style={{height:(agrees?100:60)+'%',background:agrees?'var(--mochi-pink)':'var(--mochi-orange)'}}/>})}</div>{r.fields.map(f=><div className="field-agreement" key={f.name}><span>{fieldLabel(f.name)}<br/><b>{f.value}</b></span><div className="agreement-track"><span style={{width:f.agreement+'%'}}/></div><span>{f.agreement}%</span></div>)}<div className="result-section"><details open><summary>Independent model readings</summary><div className="work-table-wrap"><table className="work-table"><thead><tr><th>Juror</th>{r.fields.map(f=><th key={f.name}>{fieldLabel(f.name)}</th>)}</tr></thead><tbody>{modelClasses.map((m,i)=><tr key={m}><td>{m}</td>{r.fields.map(f=><td key={f.name}>{f.answers[i]}</td>)}</tr>)}</tbody></table></div><p>{r.tolerance}</p></details><details><summary>Evidence spans</summary>{r.fields.map(f=><div key={f.name}><small>{f.name}</small><pre>{f.evidence}</pre></div>)}<p>Illustrative excerpts only. No cryptographic span hash is claimed.</p></details><details><summary>Attestation & receipt status</summary><pre>{['Enclave attestation: NOT CONNECTED','Model run: SAMPLE FIXTURE','Chain receipt: NOT ISSUED','Payment: NONE','Document source: FICTIONAL EXAMPLE'].join('\n')}</pre></details></div>{r.status==='HUNG'&&<p className="work-message">HUNG means the jurors did not agree; no outcome is presented. Human panels are not available at launch.</p>}<div className="work-actions"><Button onClick={()=>download({...r,sample:true,attestation:'NOT_CONNECTED',chainReceipt:null},'mochi-sample-decision-packet.json')}>Export sample packet <span>↓</span></Button><Button secondary onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(r,null,2));setMessage('Sample packet copied.')}catch{setMessage('Clipboard is unavailable. Use Export sample packet instead.')}}}>Copy JSON</Button></div></section>}
createRoot(document.getElementById('dashboard-root')).render(<DashboardEntry Sample={App}/>);
