import React,{useState,useEffect,useRef} from 'react';
import {LiveClient,json,validateConfig,formatValue} from './live-client.js';
import {schemas} from './fixtures.js';
import {SCHEMAS} from '@mochi/schemas';
const tabs=['Overview','New query','Verdicts','Feeds','Disagreement'];
const short=v=>v?`${v.slice(0,8)}…${v.slice(-6)}`:'';
function download(value,name){const url=URL.createObjectURL(new Blob([json(value)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Button({secondary,children,...props}){return <button className={'work-button'+(secondary?' secondary':'')} {...props}>{children}</button>}
function readHistory(){try{return JSON.parse(localStorage.getItem('mochi-query-ids')||'[]').filter(r=>/^0x[0-9a-f]{64}$/.test(r.queryId)).slice(0,30)}catch{return []}}
export function LiveDashboard({config}){
 // The site offers the three-juror launch review only; larger juries are configurable later.
 const jurySizes=config.jurySizes.filter(size=>size===3);
 const client=useRef(null),poller=useRef(null),secrets=useRef(new Map()),inFlight=useRef(false);
 const [tab,setTab]=useState('Overview'),[wallet,setWallet]=useState(''),[source,setSource]=useState(''),[file,setFile]=useState(null),[schema,setSchema]=useState('EARNINGS'),[n,setN]=useState(3),[privateResult,setPrivate]=useState(true),[question,setQuestion]=useState(''),[answerType,setAnswerType]=useState('BOOL'),[consensusEps,setConsensusEps]=useState(''),[consensusRevenue,setConsensusRevenue]=useState(''),[prepared,setPrepared]=useState(null),[backedUp,setBackedUp]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[result,setResult]=useState(null),[receipt,setReceipt]=useState(null),[history,setHistory]=useState(readHistory),[queryId,setQueryId]=useState(''),[data,setData]=useState(null),[feed,setFeed]=useState('corp-actions.split@RHC'),[subject,setSubject]=useState(''),[field,setField]=useState('eps_gaap_diluted');
 useEffect(()=>{client.current=new LiveClient(config);return()=>poller.current?.abort()},[config]);
 useEffect(()=>{try{localStorage.setItem('mochi-query-ids',json(history))}catch{}},[history]);
 useEffect(()=>{const warn=e=>{if(secrets.current.size){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[]);
 function invalidate(){setPrepared(null);setBackedUp(false)}
 function changeTab(t){if(busy)return;poller.current?.abort();setTab(t);setResult(null);setReceipt(null);setError('');setMessage('');setData(null);document.querySelector('[data-scroll-wrapper]')?.scrollTo({top:0})}
 // A JSON SyntaxError carries engine wording (WebKit: "The string did not match the expected pattern."), not a reason.
 async function task(fn){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(e.name!=='AbortError')setError(e.name==='SyntaxError'?'The service response could not be read. Please retry.':e.message||'The operation failed.')}finally{inFlight.current=false;setBusy(false)}}
 async function quote(e){e.preventDefault();await task(async()=>{invalidate();setMessage('Verifying intake attestation, then encrypting the document…');const bytes=file?new Uint8Array(await file.arrayBuffer()):new TextEncoder().encode(source);const p=schema==='FREEFORM_FACT'?{question,answer_type:answerType}:schema==='EARNINGS'?{...(consensusEps?{consensus_eps:consensusEps}:{}),...(consensusRevenue?{consensus_revenue:consensusRevenue}:{})}:{};setPrepared(await client.current.prepare({bytes,contentType:file?.type||'text/plain',schema,n,isPublic:!privateResult,params:p}));setMessage('Encrypted document accepted. Review the quote before paying.')})}
 async function watch(id){poller.current?.abort();poller.current=new AbortController();setResult(null);setReceipt(null);const item=await client.current.poll(id,{signal:poller.current.signal,onProgress:setMessage});setResult(await client.current.verifyResult(item,secrets.current.get(id)));setMessage('Verdict loaded. Answer verification uses the on-chain commitment.');setHistory(rows=>rows.map(r=>r.queryId===id?{...r,verdictId:item.verdictId}:r))}
 async function pay(){await task(async()=>{if(!prepared||(!prepared.isPublic&&!backedUp))throw new Error('Save the private-result recovery file first.');secrets.current.set(prepared.queryId,prepared.secrets);const row={queryId:prepared.queryId,chainId:config.chainId,escrow:config.contracts.queryEscrow,createdAt:new Date().toISOString()};setHistory(rows=>[row,...rows.filter(r=>r.queryId!==row.queryId)].slice(0,30));const hash=await client.current.submit(prepared,(text,tx)=>setMessage(tx?`${text}: ${short(tx)}`:text));setHistory(rows=>rows.map(r=>r.queryId===row.queryId?{...r,tx:hash}:r));setQueryId(row.queryId);setPrepared(null);await watch(row.queryId)})}
 async function recover(e){const f=e.target.files?.[0];if(!f)return;await task(async()=>{if(f.size>8192)throw new Error('Recovery file is too large.');let saved;try{saved=JSON.parse(await f.text())}catch{throw new Error('Recovery file is not valid JSON.')}if(saved.kind!=='MOCHI_QUERY_RECOVERY'||saved.chainId!==config.chainId||saved.escrow?.toLowerCase()!==config.contracts.queryEscrow.toLowerCase()||!/^0x[0-9a-f]{64}$/.test(saved.queryId)||!/^0x[0-9a-f]{64}$/.test(saved.secrets?.salt)||!/^0x[0-9a-f]{64}$/.test(saved.secrets?.resultPrivateKey))throw new Error('Recovery file does not match this deployment.');secrets.current.set(saved.queryId,saved.secrets);setQueryId(saved.queryId);await watch(saved.queryId)});e.target.value=''}
 const rows=history.filter(r=>r.chainId===config.chainId&&r.escrow?.toLowerCase()===config.contracts.queryEscrow.toLowerCase());
 return <div className="workspace"><aside className="workspace-rail"><div className="rail-brand">MOCHI<small>Model jury workspace</small></div><nav className="workspace-tabs" aria-label="Workspace">{tabs.map(t=><button key={t} disabled={busy} className={tab===t?'active':''} onClick={()=>changeTab(t)}>{t}</button>)}</nav><div className="rail-footer"><p>{config.chainId===4663?'Mainnet':'Test network'} · {config.chainId}<br/>Query IDs stay on this device.</p><a href="/dashboard/?mode=sample">Explore sample workspace ↗</a><br/><a href="/docs/">Developer documentation ↗</a></div></aside>
 <div className="workspace-body"><div className="workspace-kicker"><span>● {config.chainId===4663?'MAINNET':'TEST NETWORK'}</span><span>MOCHI / {String(tabs.indexOf(tab)+1).padStart(2,'0')}</span></div><h1 className="workspace-title">{tab==='Overview'?'Review overview.':tab==='New query'?'Prepare a review.':tab+'.'}</h1><p className="workspace-note">Documents are encrypted in this browser to the verified intake enclave. USDG payments are visible on chain; private results are encrypted to your recovery key.</p><div className="work-actions"><Button secondary disabled={busy} onClick={()=>task(async()=>{setWallet(await client.current.connect());invalidate();setMessage('Wallet connected. No payment was requested.')})}>{wallet?`Wallet ${short(wallet)}`:'Connect wallet'}</Button></div>
 {error&&<div role="alert" className="work-message error">{error}</div>}{message&&<div role="status" className="work-message">{message}</div>}
 {tab==='Overview'&&<><div className="workspace-stats"><div className="workspace-stat"><strong>07</strong><span>Document schemas</span></div><div className="workspace-stat"><strong>03</strong><span>AI jurors at launch</span></div><div className="workspace-stat"><strong>100%</strong><span>Agreement required: all 3 jurors</span></div></div><Button disabled={busy} onClick={()=>changeTab('New query')}>Prepare a review →</Button><h2>Network activity</h2><Button secondary disabled={busy} onClick={()=>task(async()=>setData(await client.current.request('/api/v1/stats')))}>Load current activity</Button><p>No activity is shown until it is retrieved from the network.</p></>}
 {tab==='New query'&&<><form className="work-form" onSubmit={quote}><fieldset disabled={busy} style={{display:'contents'}}><div className="field-row"><label>Task schema<select value={schema} onChange={e=>{setSchema(e.target.value);invalidate()}}>{schemas.map(s=><option key={s}>{s}</option>)}</select></label><label>Jury size<select value={n} onChange={e=>{setN(Number(e.target.value));invalidate()}}>{jurySizes.map(n=><option key={n} value={n}>{n} AI jurors</option>)}</select><small>{jurySizes.length?'Larger juries, up to 9, are configurable later.':'This deployment does not offer the three-juror review.'}</small></label></div><label>Document text<textarea value={source} disabled={!!file} maxLength={100000} onChange={e=>{setSource(e.target.value);invalidate()}} placeholder="Paste a document or choose a file below."/></label><label>Document file, up to 100 KB<input type="file" accept=".txt,.md,.csv,.pdf" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>100000){setError('Use a file smaller than 100 KB.');e.target.value='';return}setFile(f??null);invalidate()}}/></label>{file&&<Button type="button" secondary onClick={()=>{setFile(null);invalidate()}}>Use pasted text instead</Button>}{schema==='FREEFORM_FACT'&&<><label>Your question<input value={question} onChange={e=>{setQuestion(e.target.value);invalidate()}} required/></label><label>Answer format<select value={answerType} onChange={e=>{setAnswerType(e.target.value);invalidate()}}><option value="BOOL">Yes or no</option><option value="NUMBER">Number</option><option value="STRING">Text</option></select></label></>}{schema==='EARNINGS'&&<div className="field-row"><label>Expected EPS (optional)<input value={consensusEps} onChange={e=>{setConsensusEps(e.target.value);invalidate()}}/></label><label>Expected revenue (optional)<input value={consensusRevenue} onChange={e=>{setConsensusRevenue(e.target.value);invalidate()}}/></label></div>}<label className="check-field"><input type="checkbox" checked={privateResult} onChange={e=>{setPrivate(e.target.checked);invalidate()}}/><span>Keep the result private<br/><small>Only your recovery key can decrypt it. Wallet payment is still public. Human-panel disclosure is off.</small></span></label><Button disabled={!wallet||busy||!jurySizes.length} type="submit">{busy?'Preparing…':'Encrypt document and get quote'} →</Button></fieldset></form>
 {prepared&&<section className="work-result"><h2>{prepared.displayAmount} USDG</h2><p>{prepared.n} jurors · {prepared.tokensK} thousand-token units · wallet gas fees are additional. Quote expires in five minutes.</p>{!prepared.isPublic&&<><p>Save your recovery file before paying. Keep it private. Keys and decrypted results are never saved to browser storage.</p><Button secondary disabled={busy} onClick={()=>{download({kind:'MOCHI_QUERY_RECOVERY',chainId:config.chainId,escrow:prepared.escrow,queryId:prepared.queryId,secrets:prepared.secrets},`mochi-recovery-${prepared.queryId.slice(2,10)}.json`);setBackedUp(true)}}>Save recovery file ↓</Button></>}<div className="work-actions"><Button disabled={busy||(!prepared.isPublic&&!backedUp)} onClick={pay}>Pay {prepared.displayAmount} USDG and start review →</Button><Button secondary disabled={busy} onClick={invalidate}>Discard quote</Button></div></section>}</>}
 {tab==='Verdicts'&&<><form className="work-form" onSubmit={e=>{e.preventDefault();task(()=>watch(queryId.trim()))}}><label>Query ID<input value={queryId} onChange={e=>setQueryId(e.target.value)} placeholder="0x…" required/></label><Button disabled={busy} type="submit">Resume query</Button><label>Load private-result recovery file<input type="file" accept=".json" disabled={busy} onChange={recover}/></label></form><h2>Queries from this device</h2>{rows.length?<div className="work-table-wrap"><table className="work-table"><thead><tr><th>Query</th><th>Created</th><th>State</th></tr></thead><tbody>{rows.map(r=><tr key={r.queryId}><td><button disabled={busy} onClick={()=>task(()=>watch(r.queryId))}>{short(r.queryId)}</button></td><td>{new Date(r.createdAt).toLocaleString()}</td><td>{r.verdictId?'Verdict available':r.tx?'Submitted':'Submission attempted'}</td></tr>)}</tbody></table></div>:<p>No saved query IDs for this deployment.</p>}</>}
 {tab==='Feeds'&&<form className="work-form" onSubmit={e=>{e.preventDefault();task(async()=>{if(!subject.trim())throw new Error('Enter a ticker or subject key.');setData(await client.current.request(`/api/v1/feeds/${encodeURIComponent(feed)}/${encodeURIComponent(subject.trim())}`))})}}><label>Feed name<input value={feed} onChange={e=>setFeed(e.target.value)}/></label><label>Ticker or subject key<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="NVDA"/></label><Button disabled={busy}>Load latest feed record</Button><p>This reads the feed. It does not purchase a subscription.</p></form>}
 {tab==='Disagreement'&&<form className="work-form" onSubmit={e=>{e.preventDefault();task(async()=>{const q=new URLSearchParams({schema:String(Object.values(SCHEMAS).find(s=>s.name===schema).id),field,window:'7d'});setData(await client.current.request(`/api/v1/disagreement?${q}`))})}}><label>Schema<select value={schema} onChange={e=>setSchema(e.target.value)}>{schemas.map(s=><option key={s}>{s}</option>)}</select></label><label>Field<input value={field} onChange={e=>setField(e.target.value)}/></label><Button disabled={busy}>Load disagreement data</Button></form>}
 {data&&<pre className="mochi-code">{json(data)}</pre>}
 {busy&&poller.current&&!poller.current.signal.aborted&&<Button secondary onClick={()=>{poller.current.abort();setMessage('Stopped waiting. The on-chain review continues; resume by query ID.')}}>Stop waiting</Button>}
 {result&&<section className="work-result"><div className="result-top"><div><small>DECISION PACKET / {result.chain.isPublic?'PUBLIC':'PRIVATE'}</small><h2>{Number(result.chain.status)===1?'VERDICT':'HUNG'}</h2><p>{short(result.verdictId)}</p></div><strong>{Number(result.chain.agreementBps)/100}%<small>Minimum field agreement</small></strong></div>{result.locked?<p>Load the recovery file to decrypt this result. The service retains encrypted results for seven days.</p>:<><p>Answer hash verified against the on-chain verdict.</p><div className="work-table-wrap"><table className="work-table"><thead><tr><th>Field</th><th>Agreed value</th></tr></thead><tbody>{Object.entries(result.answer.fields??{}).map(([name,value])=><tr key={name}><td>{name.replaceAll('_',' ')}</td><td>{formatValue(value)}</td></tr>)}</tbody></table></div></>}<details><summary>On-chain evidence</summary><pre className="mochi-code">{json(result.chain)}</pre></details><div className="work-actions"><Button secondary disabled={busy} onClick={()=>task(async()=>setReceipt(await client.current.receipt(result.verdictId)))}>Verify receipt and anchor</Button>{!result.locked&&<Button onClick={()=>download({verdictId:result.verdictId,chain:result.chain,answer:result.answer},'mochi-decision.json')}>Export decision ↓</Button>}</div>{receipt&&<p>Receipt signature verified. {receipt.anchored?'Anchor confirmed on chain.':'Not yet anchored on chain.'}</p>}{Number(result.chain.status)===2&&<p>This review is unresolved. No answer or feed update should be treated as agreed. This dashboard does not purchase additional seats.</p>}</section>}
 </div></div>
}
// Messages from this error type are written for visitors; anything else (a network TypeError, a JSON SyntaxError)
// gets a generic message. WebKit reports invalid JSON as "The string did not match the expected pattern."
class ConfigLoadError extends Error {}
async function loadDeployment(signal){
 const r=await fetch('/mochi-config.json',{cache:'no-store',signal});
 if(r.status===404)return null;
 if(!r.ok)throw new ConfigLoadError('Deployment configuration is unavailable.');
 // A proxy or dev server can answer with an HTML page instead of JSON.
 let c;try{c=await r.json()}catch(e){if(e?.name==='AbortError')throw e;throw new ConfigLoadError('Deployment configuration could not be read.')}
 if(c?.enabled===false)return null;
 try{return validateConfig(c)}catch(e){throw new ConfigLoadError(e.message)}
}
// A stalled config request must not leave visitors on "Loading deployment…" with no way forward.
const CONFIG_TIMEOUT_MS=8000;
function EntryShell({kicker,actions,children}){return <div className="workspace"><aside className="workspace-rail"><div className="rail-brand">MOCHI<small>Model jury workspace</small></div><a href="/">Back to MOCHI ↗</a></aside><div className="workspace-body"><div className="workspace-kicker">{kicker}</div><h1 className="workspace-title">Review workspace.</h1>{children}<div className="work-actions">{actions}<a className="work-button" href="/dashboard/?mode=sample">Explore sample workspace ↗</a></div></div></div>}
export function DashboardEntry({Sample}){
 const [config,setConfig]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 const sample=new URLSearchParams(location.search).get('mode')==='sample'||new URLSearchParams(location.search).has('sample');
 useEffect(()=>{if(sample){setReady(true);return}setReady(false);setError('');const abort=new AbortController();let timedOut=false;const timer=setTimeout(()=>{timedOut=true;abort.abort()},CONFIG_TIMEOUT_MS);loadDeployment(abort.signal).then(c=>{if(c)setConfig(c)}).catch(e=>{if(timedOut)setError('The deployment configuration did not load in time.');else if(e.name!=='AbortError')setError(e instanceof ConfigLoadError?e.message:'Deployment configuration could not be loaded.')}).finally(()=>{clearTimeout(timer);if(timedOut||!abort.signal.aborted)setReady(true)});return()=>{clearTimeout(timer);abort.abort()}},[sample,attempt]);
 if(sample)return <Sample/>;
 if(!ready)return <EntryShell kicker="CHECKING DEPLOYMENT"><p className="workspace-note" role="status">Loading deployment…</p><p>The clearly labelled sample workspace is available while this loads.</p></EntryShell>;
 if(config)return <LiveDashboard config={config}/>;
 return <EntryShell kicker={error?'DEPLOYMENT STATUS UNAVAILABLE':'DEPLOYMENT PENDING'} actions={error&&<Button secondary onClick={()=>setAttempt(n=>n+1)}>Retry ↻</Button>}><p className="workspace-note">The live workspace opens when the verified deployment is configured. You can explore clearly labelled samples now.</p><p>Planned launch pricing starts at $0.10 USDG for a three-juror review of up to 1,000 estimated document tokens. Larger documents and juries cost more; network gas is additional.</p>{error&&<p role="alert" className="work-message error">{error}</p>}</EntryShell>;
}
